/**
 * @file src/types.ts
 * @description This file contains comprehensive TypeScript interfaces and type definitions for the entire application.
 * It ensures type safety and provides a clear data contract for developers and AI agents interacting with the system.
 * The types cover Cloudflare environment bindings, database schemas, API request/response formats, and WebSocket messages.
 */

/**
 * @interface Env (Generated by wrangler types)
 * @description The Env interface is automatically generated by `wrangler types` and available globally.
 * It defines the structure of the Cloudflare Worker's environment bindings based on your wrangler.toml configuration.
 * 
 * The generated interface includes:
 * - Bindings to Cloudflare services (AI, D1, R2, Browser Rendering)
 * - Environment variables from [vars] section
 * - Secret variables for authentication
 * 
 * Documentation of expected properties (actual interface is in worker-configuration.d.ts):
 */
interface EnvDocumentation {
  /** 
   * @description Binding for Cloudflare's AI services, used for running vision and language models.
   * @see https://developers.cloudflare.com/workers-ai/
   */
  AI: Ai;
  
  /** 
   * @description Binding for the Browser Rendering API, used to control a headless browser instance with Puppeteer.
   * @see https://developers.cloudflare.com/browser-rendering/
   */
  BROWSER: Fetcher;
  
  /** 
   * @description Binding for a D1 database, used for storing configuration and job metadata.
   * @see https://developers.cloudflare.com/d1/
   */
  DB: D1Database;
  
  /** 
   * @description Binding for an R2 bucket, used for storing assets like screenshots and HTML files.
   * @see https://developers.cloudflare.com/r2/
   */
  R2_BUCKET: R2Bucket;
  
  /** 
   * @description Optional binding for a KV namespace, for key-value storage.
   * @see https://developers.cloudflare.com/kv/
   */
  KV?: KVNamespace;
  
  // --- Environment variables ---
  /** 
   * @description The public base URL for the R2 bucket, configured in wrangler.toml.
   * Used for generating public URLs for stored assets.
   */
  BUCKET_PUBLIC_BASE_URL: string;
  
  // --- Secret environment variables for authentication ---
  /** @description Secret containing the username for LinkedIn. Set via `wrangler secret put`. */
  LINKEDIN_USERNAME?: string;
  /** @description Secret containing the password for LinkedIn. Set via `wrangler secret put`. */
  LINKEDIN_PASSWORD?: string;
  /** @description Secret containing the username for Indeed. */
  INDEED_USERNAME?: string;
  /** @description Secret containing the password for Indeed. */
  INDEED_PASSWORD?: string;
  /** @description Secret containing the username for Glassdoor. */
  GLASSDOR_USERNAME?: string;
  /** @description Secret containing the password for Glassdoor. */
  GLASSDOOR_PASSWORD?: string;
  
  // --- Model configurations ---
  /** @description The identifier for the vision model to be used (e.g., '@cf/llava-hf/llava-1.5-7b-hf'). */
  VISION_MODEL?: string;
  /** @description The identifier for the reasoning/language model to be used (e.g., '@cf/meta/llama-4-scout-17b-16e-instruct'). */
  REASONING_MODEL?: string;
  
  /** @description The URL for the WebSocket server for real-time updates. */
  WEBSOCKET_URL?: string;
  
  /** 
   * @description Allows for dynamic access to other secret variables, enabling support for various sites.
   * The key should correspond to the `username_secret_var` or `password_secret_var` in the `site_config` table.
   */
  [key: string]: any;
}

/**
 * @interface SiteConfig
 * @description Represents the configuration for a specific job site, stored in the D1 database.
 * This configuration defines how to authenticate and interact with a site.
 */
export interface SiteConfig {
  /** @description The unique identifier for the site configuration. */
  id: number;
  /** @description A SQL LIKE pattern to match against job posting URLs (e.g., '%linkedin.com/jobs/view/%'). */
  url_pattern: string;
  /** @description The name of the secret variable in `Env` that holds the username for this site. */
  username_secret_var: string;
  /** @description The name of the secret variable in `Env` that holds the password for this site. */
  password_secret_var: string;
  /** @description The direct URL to the site's login page. */
  login_url: string;
  /** @description Optional, site-specific instructions for the AI agent to handle complex login flows. */
  login_agent_instructions?: string;
  /** @description The timestamp when the configuration was created. */
  created_at: string;
  /** @description The timestamp when the configuration was last updated. */
  updated_at: string;
}

/**
 * @interface JobConfig
 * @description Defines the parameters for a specific scraping job, stored in the D1 database.
 */
export interface JobConfig {
  /** @description The unique identifier for the job configuration. */
  id: number;
  /** @description The timestamp when the job was configured. */
  timestamp: string;
  /** @description Custom instructions for the AI agent to guide the extraction process. */
  agent_instructions?: string;
  /** @description The initial URL where the scraping should begin. */
  starting_url: string;
  /** @description A flag to determine if a PDF of the job posting should be collected. */
  collect_pdf: boolean;
  /** @description A flag to determine if the extracted JSON data should be saved. */
  collect_json: boolean;
  /** @description A flag to determine if the raw HTML of the page should be saved. */
  collect_html: boolean;
  /** @description A flag to determine if a screenshot of the page should be captured. */
  collect_screenshot: boolean;
}

/**
 * @interface ScrapeJob
 * @description Represents a single scraping job instance, tracking its status and metadata in the D1 database.
 */
export interface ScrapeJob {
  /** @description The unique identifier for this specific scrape instance. */
  id: number;
  /** @description A foreign key linking to the `JobConfig` used for this scrape. */
  job_config_id: number;
  /** @description An optional foreign key linking to the `SiteConfig` if authentication was required. */
  site_config_id?: number;
  /** @description The timestamp when the scrape job was created. */
  timestamp: string;
  /** @description The full URL of the target page that was scraped. */
  full_url: string;
  /** @description The base URL (hostname) of the target page. */
  base_url: string;
  /** @description The current status of the scraping job. */
  status: 'not_started' | 'in_progress' | 'complete' | 'error';
  /** @description A log of details or error messages related to the job's execution. */
  log_details?: string;
  /** @description The timestamp when the job was completed or failed. */
  completed_at?: string;
}

/**
 * @interface ExtractedAsset
 * @description Represents an asset (e.g., screenshot, HTML file) generated during a scrape and stored in R2.
 * Its metadata is stored in the D1 database.
 */
export interface ExtractedAsset {
  /** @description The unique identifier for the asset. */
  id: number;
  /** @description A foreign key linking to the `ScrapeJob` that generated this asset. */
  scrape_id: number;
  /** @description The name of the asset file. */
  name: string;
  /** @description The type of the asset (e.g., 'json', 'html', 'screenshot', 'vision-screenshot'). */
  type: string;
  /** @description The key (path) of the asset within the R2 bucket. */
  r2_key: string;
  /** @description The public URL to access the asset from R2. */
  r2_url: string;
  /** @description An optional MD5 hash for verifying file integrity. */
  md5_hash?: string;
  /** @description The size of the file in bytes. */
  filesize?: number;
  /** @description The timestamp when the asset was created. */
  created_at: string;
}

/**
 * @interface JobExtractionRequest
 * @description Defines the structure for an API request to extract job data from a URL.
 */
export interface JobExtractionRequest {
  /** @description The target URL of the job posting to be scraped. */
  url: string;
  /** @description Optional parameters to customize the extraction process. */
  options?: {
    /** @description If true, a screenshot of the final page will be captured and stored. */
    includeScreenshot?: boolean;
    /** @description If true, the raw HTML of the final page will be captured and stored. */
    includeHtml?: boolean;
    /** @description Custom instructions to override the default AI agent behavior for this specific request. */
    customInstructions?: string;
    /** @description If true, the system will wait for any necessary authentication to complete before proceeding. */
    waitForAuth?: boolean;
  };
}

/**
 * @interface JobExtractionResponse
 * @description Defines the standardized response format for all job extraction operations.
 */
export interface JobExtractionResponse {
  /** @description A boolean indicating whether the operation was successful. */
  success: boolean;
  /** @description The extracted and structured job data, conforming to the `jobPostingSchema`. Present on success. */
  data?: any;
  /** @description A human-readable summary of the job posting, generated by the AI. */
  summary?: string;
  /** @description An array of assets that were generated and stored during the process. */
  assets?: ExtractedAsset[];
  /** @description A descriptive error message if the operation failed. */
  error?: string;
  /** @description The total time taken for the operation, in milliseconds. */
  processingTime?: number;
}

/**
 * @interface AuthenticationResult
 * @description Represents the outcome of an automated authentication attempt.
 */
export interface AuthenticationResult {
  /** @description A boolean indicating if the authentication was successful. */
  success: boolean;
  /** @description A message describing the outcome. */
  message: string;
  /** @description If true, indicates that the authentication flow requires manual intervention. */
  requiresManualIntervention?: boolean;
  /** @description The type of challenge encountered (e.g., '2fa', 'captcha') if authentication failed or requires intervention. */
  challengeType?: '2fa' | 'captcha' | 'security_check' | 'unknown';
}

/**
 * @interface WebSocketMessage
 * @description Defines the structure for messages sent over the WebSocket connection for real-time updates.
 */
export interface WebSocketMessage {
  /** @description The type of message, indicating its purpose. */
  type: 'status_update' | 'vision_update' | 'error' | 'complete';
  /** @description The ID of the job this message pertains to. */
  jobId: number;
  /** @description A human-readable message. */
  message: string;
  /** @description Optional data payload associated with the message. */
  data?: any;
  /** @description The timestamp when the message was generated. */
  timestamp: string;
}

/**
 * @interface ScrapingOptions
 * @description Defines a set of configurable options for a scraping operation.
 */
export interface ScrapingOptions {
  /** @description The maximum number of times to retry a failed operation. */
  maxRetries?: number;
  /** @description The timeout in milliseconds for network requests. */
  timeout?: number;
  /** @description A flag to explicitly wait for authentication if required. */
  waitForAuth?: boolean;
  /** @description Custom instructions for the AI agent for this specific scrape. */
  customInstructions?: string;
  /** @description Specifies which types of assets to include in the output. */
  includeAssets?: {
    screenshot?: boolean;
    html?: boolean;
    pdf?: boolean;
  };
}

/**
 * @interface VisionAnalysisOptions
 * @description Defines options for the vision analysis service.
 */
export interface VisionAnalysisOptions {
  /** @description If true, a screenshot of the full page is taken; otherwise, only the viewport is captured. */
  fullPage?: boolean;
  /** @description The quality of the screenshot, which can affect performance and model accuracy. */
  quality?: 'low' | 'medium' | 'high';
  /** @description If true, includes additional context (like URL, page title) in the prompt to the vision model. */
  includeContext?: boolean;
}

/**
 * Note: The Env interface is globally available from worker-configuration.d.ts
 * 
 * No need to import or export Env - it's automatically available in all TypeScript files
 * when worker-configuration.d.ts is included in tsconfig.json types array.
 */